/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projefsm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Motasem
 */
public class AdminChannels extends javax.swing.JFrame { // Adminlarin sayfalrind insert update select delete delete all ve reset islemleri yapiliyor
    
    Connection con;
    PreparedStatement ps;
    Statement st;
    java.sql.ResultSet rst;

    /**
     * Creates new form AdminChannels
     */
    public AdminChannels() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1insert = new javax.swing.JButton();
        jButton2updatr = new javax.swing.JButton();
        jButton3DeleteAll = new javax.swing.JButton();
        jButton4Delete = new javax.swing.JButton();
        jButton1reset = new javax.swing.JButton();
        jTextField1Channel = new javax.swing.JTextField();
        jTextField2Link = new javax.swing.JTextField();
        jButton1show = new javax.swing.JButton();
        jButton1Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Channel Name", "Link"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jButton1insert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1insert.setForeground(new java.awt.Color(0, 0, 0));
        jButton1insert.setText("insert");
        jButton1insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1insertActionPerformed(evt);
            }
        });

        jButton2updatr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2updatr.setForeground(new java.awt.Color(0, 0, 0));
        jButton2updatr.setText("Update");
        jButton2updatr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2updatrActionPerformed(evt);
            }
        });

        jButton3DeleteAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3DeleteAll.setForeground(new java.awt.Color(0, 0, 0));
        jButton3DeleteAll.setText("Delete All");
        jButton3DeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DeleteAllActionPerformed(evt);
            }
        });

        jButton4Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4Delete.setForeground(new java.awt.Color(0, 0, 0));
        jButton4Delete.setText("Delete");
        jButton4Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4DeleteActionPerformed(evt);
            }
        });

        jButton1reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1reset.setForeground(new java.awt.Color(0, 0, 0));
        jButton1reset.setText("Reset");
        jButton1reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1resetActionPerformed(evt);
            }
        });

        jTextField1Channel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField1Channel.setForeground(new java.awt.Color(0, 0, 102));

        jTextField2Link.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField2Link.setForeground(new java.awt.Color(0, 0, 102));
        jTextField2Link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2LinkActionPerformed(evt);
            }
        });

        jButton1show.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1show.setForeground(new java.awt.Color(0, 0, 0));
        jButton1show.setText("show");
        jButton1show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1showActionPerformed(evt);
            }
        });

        jButton1Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1Back.setForeground(new java.awt.Color(0, 0, 102));
        jButton1Back.setText("Back");
        jButton1Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3DeleteAll)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4Delete)
                                .addComponent(jButton2updatr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1show, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1reset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1insert, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1Channel, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(jTextField2Link))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jTextField1Channel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1insert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2Link, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1reset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1show, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2updatr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(jButton4Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton3DeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jButton1Back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1insertActionPerformed
        // TODO add your handling code here:

        try {
            Connection con = MakeCon.MakeConnection();
            String sql = "INSERT INTO mysql.adminchannel(ChannelName,Link) VALUES (?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jTextField1Channel.getText());
            pst.setString(2, jTextField2Link.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "inserted");


        } catch (SQLException ex) {
            System.out.println("Not inserted");
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_jButton1insertActionPerformed

    private void jButton2updatrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2updatrActionPerformed
        // TODO add your handling code here: // tablede sectigimiz satir bilgileri guncellemek icin
        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) jTable1.getModel();

        int indx = jTable1.getSelectedRow();

        try {
            Connection con = MakeCon.MakeConnection();

            String originalChannel = model.getValueAt(indx, 0).toString(); // hangi satiri update yapcagina burdan  bagladim ,

            String sql = "UPDATE mysql.adminchannel SET ChannelName = ?,Link = ? WHERE ChannelName = ?";

            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(3, originalChannel);
            ps.setString(1, jTextField1Channel.getText());
            ps.setString(2, jTextField2Link.getText());
            

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jButton2updatrActionPerformed

    private void jButton3DeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3DeleteAllActionPerformed
        // TODO add your handling code here:
        Connection con = MakeCon.MakeConnection();

        try {
            String sql = "DELETE FROM mysql.adminchannel";

            ps = con.prepareStatement(sql);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"Deleted");

        } catch (Exception e) {

            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3DeleteAllActionPerformed

    private void jButton4DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4DeleteActionPerformed
        // TODO add your handling code here:
        Connection con = MakeCon.MakeConnection();

        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) jTable1.getModel();

        int indx = jTable1.getSelectedRow();

        try {

            String sql = "DELETE FROM mysql.adminchannel WHERE ChannelName = ? ";

            ps = con.prepareStatement(sql);

            ps.setString(1, model.getValueAt(indx, 0).toString());

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"Deleted");

        } catch (Exception e) {

            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_jButton4DeleteActionPerformed

    private void jButton1resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1resetActionPerformed
        // TODO add your handling code here:
        jTextField1Channel.setText("");
        jTextField2Link.setText("");
        
    }//GEN-LAST:event_jButton1resetActionPerformed

    private void jTextField2LinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2LinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2LinkActionPerformed

    private void jButton1showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1showActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0); // show button bir daha basarsak satirlarin sayisi 0 olacak sonra sadece database tabledaki bilgileri yani satirlari yazdiracak
        model = (DefaultTableModel)jTable1.getModel();

        try {
            model.setRowCount(0);
            String sql = "SELECT * FROM mysql.adminchannel ";
            Connection con = MakeCon.MakeConnection();
            ps = con.prepareStatement(sql);
            rst = ps.executeQuery();

            while (rst.next()) {
                model.addRow(new Object[]{rst.getString(1) , rst.getString(2)});
            }

        } catch (SQLException ex) {

            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_jButton1showActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel) jTable1.getModel();
        
        int indx = jTable1.getSelectedRow();                     // sectigimiz satrin bilgileri textfiealdlerde yazdiriyor
        
        jTextField1Channel.setText(model.getValueAt(indx, 0).toString());
        jTextField2Link.setText(model.getValueAt(indx, 1).toString()); 
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BackActionPerformed
        // TODO add your handling code here:
        MainMenuAdmin x = new MainMenuAdmin();

        x.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_jButton1BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChannels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChannels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChannels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChannels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChannels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Back;
    private javax.swing.JButton jButton1insert;
    private javax.swing.JButton jButton1reset;
    private javax.swing.JButton jButton1show;
    private javax.swing.JButton jButton2updatr;
    private javax.swing.JButton jButton3DeleteAll;
    private javax.swing.JButton jButton4Delete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1Channel;
    private javax.swing.JTextField jTextField2Link;
    // End of variables declaration//GEN-END:variables
}
