/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projefsm;

/**
 *
 * @author Motasem
 */
public class MainMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuAdmin
     */
    public MainMenuAdmin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1userInformatio = new javax.swing.JButton();
        jButton2addmatch = new javax.swing.JButton();
        jButton1addchanel1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1editstanding1 = new javax.swing.JButton();
        jButton1UserMesage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton1userInformatio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1userInformatio.setForeground(new java.awt.Color(51, 0, 102));
        jButton1userInformatio.setText("USERS INFORMATIONS");
        jButton1userInformatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1userInformatioActionPerformed(evt);
            }
        });

        jButton2addmatch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2addmatch.setForeground(new java.awt.Color(51, 0, 102));
        jButton2addmatch.setText("ADD MATCHES AND SCORES");
        jButton2addmatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2addmatchActionPerformed(evt);
            }
        });

        jButton1addchanel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1addchanel1.setForeground(new java.awt.Color(51, 0, 102));
        jButton1addchanel1.setText("ADD CHANNEL");
        jButton1addchanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1addchanel1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROGRAM CONTROL CENTER");

        jButton1editstanding1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1editstanding1.setForeground(new java.awt.Color(51, 0, 102));
        jButton1editstanding1.setText("EDIT STANDING TABLE");
        jButton1editstanding1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1editstanding1ActionPerformed(evt);
            }
        });

        jButton1UserMesage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1UserMesage.setForeground(new java.awt.Color(0, 0, 102));
        jButton1UserMesage.setText("USERS MESSAGES");
        jButton1UserMesage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1UserMesageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1editstanding1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1addchanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2addmatch, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1userInformatio, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(jButton1UserMesage)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2addmatch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1UserMesage, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1addchanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButton1editstanding1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jButton1userInformatio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2addmatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2addmatchActionPerformed
        // TODO add your handling code here:
        AdminMatchCylinder x = new AdminMatchCylinder();
        
        x.setVisible(true); // AdminMatchCylinder jframi acilsin
        
        this.setVisible(false); //MainMenuAdmin jframi kapatilsin
    }//GEN-LAST:event_jButton2addmatchActionPerformed

    private void jButton1addchanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1addchanel1ActionPerformed
        // TODO add your handling code here:
        AdminChannels x = new AdminChannels();
        
        x.setVisible(true); // AdminChannels jframi acilsin
        this.setVisible(false);  //MainMenuAdmin jframi kapatilsin
    }//GEN-LAST:event_jButton1addchanel1ActionPerformed

    private void jButton1editstanding1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1editstanding1ActionPerformed
        // TODO add your handling code here:
         AdminSatndigTable x = new AdminSatndigTable();
        
        x.setVisible(true); // AdminStandingTable jframi acilsin
        this.setVisible(false);  //MainMenuAdmin jframi kapatilsin
        
    }//GEN-LAST:event_jButton1editstanding1ActionPerformed

    private void jButton1userInformatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1userInformatioActionPerformed
        // TODO add your handling code here:
        UserInformation x = new UserInformation();
        
        x.setVisible(true); // UserInformation jframi acilsin
        this.setVisible(false);  //MainMenuAdmin jframi kapatilsin
    }//GEN-LAST:event_jButton1userInformatioActionPerformed

    private void jButton1UserMesageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1UserMesageActionPerformed
        // TODO add your handling code here:
        UsersMessages  x =new UsersMessages();
        
        x.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1UserMesageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1UserMesage;
    private javax.swing.JButton jButton1addchanel1;
    private javax.swing.JButton jButton1editstanding1;
    private javax.swing.JButton jButton1userInformatio;
    private javax.swing.JButton jButton2addmatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
