/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projefsm;

import javax.swing.JLabel;

/**
 *
 * @author Motasem
 */
public class MainMenuUser extends javax.swing.JFrame {  // CHANGE THE PLANE AND LAPEL CLOUR WHEN THE USER PRESS THE MENU

    /**
     * Creates new form MainMenuUser
     */
    public MainMenuUser() {
        initComponents();
    }

    public JLabel getjLabel1Username() {
        return jLabel1Username;
    }

    public void setjLabel1Username(JLabel jLabel1Username) {
        this.jLabel1Username = jLabel1Username;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1Username = new javax.swing.JLabel();
        jButtonyourinfo = new javax.swing.JButton();
        jButton2dailymatch = new javax.swing.JButton();
        jButtonLiveChannels1 = new javax.swing.JButton();
        jButtonstandingtable = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1Username.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1Username.setForeground(new java.awt.Color(51, 0, 102));

        jButtonyourinfo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonyourinfo.setForeground(new java.awt.Color(51, 0, 102));
        jButtonyourinfo.setText("YOUR INFORMATION");
        jButtonyourinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonyourinfoActionPerformed(evt);
            }
        });

        jButton2dailymatch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2dailymatch.setForeground(new java.awt.Color(51, 0, 102));
        jButton2dailymatch.setText("DAILY MATCH CALENDAR");
        jButton2dailymatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2dailymatchActionPerformed(evt);
            }
        });

        jButtonLiveChannels1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonLiveChannels1.setForeground(new java.awt.Color(51, 0, 102));
        jButtonLiveChannels1.setText("LIVE CHANNELS");
        jButtonLiveChannels1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiveChannels1ActionPerformed(evt);
            }
        });

        jButtonstandingtable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonstandingtable.setForeground(new java.awt.Color(51, 0, 102));
        jButtonstandingtable.setText("STANDING TABLE");
        jButtonstandingtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstandingtableActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2dailymatch, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonstandingtable, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonyourinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLiveChannels1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(jLabel1Username, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1Username))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2dailymatch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLiveChannels1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonstandingtable, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonyourinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                    ////////// main menu admin sayafasinda yaptigimiz gibi buttonlari basinca baska sayfalr acilacak ve main menu kapatilacak
    private void jButton2dailymatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2dailymatchActionPerformed
        // TODO add your handling code here:
        UserMatchClyinder x = new UserMatchClyinder();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2dailymatchActionPerformed

    private void jButtonLiveChannels1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiveChannels1ActionPerformed
        // TODO add your handling code here:
        Channels x = new Channels();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLiveChannels1ActionPerformed

    private void jButtonstandingtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstandingtableActionPerformed
        // TODO add your handling code here:
        UserStandingTable x = new UserStandingTable();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonstandingtableActionPerformed

    private void jButtonyourinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonyourinfoActionPerformed
        // TODO add your handling code here:
        YourInformation x = new YourInformation();
        x.setVisible(true);
        this.setVisible(false);
        
        x.getjLabel12PutUserName().setText(jLabel1Username.getText()); //////////////// importent//////////////
        // user "yourinformation" sayfasina girdiginde "yourinformation"de userin adi main menudaki welcomein yaninda user name aynisi yazdiralacak sonra user namei diger bilgileri syafada yazdirmak icin kullanacgim (Databasele user name kullanark connection yapacagim  
    }//GEN-LAST:event_jButtonyourinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2dailymatch;
    private javax.swing.JButton jButtonLiveChannels1;
    private javax.swing.JButton jButtonstandingtable;
    private javax.swing.JButton jButtonyourinfo;
    private javax.swing.JLabel jLabel1Username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
